apiVersion: apps/v1
kind: Deployment # db deployments usually use stateful set, or totally outside of K8s realm 
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template: # configures a pod
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        env:
        - name: MONGO_INIT_DB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INIT_DB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: mongo-secret
              key: mongo-pwd
        ports:
        - containerPort: 27017 # starts at this port as per image specs
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # this is the end point that we defined in mongi-config.yaml
spec:
  selector: # uses this label selector to match right pod
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # matches the container port