apiVersion: apps/v1
kind: Deployment # db deployments usually use stateful set, or totally outside of K8s realm 
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template: # configures a pod
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000 # starts at this port as per image specs
        env:
          - name: USER_NAME
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: mongo-user
          - name: USER_PWD
            valueFrom: 
              secretKeyRef: 
                name: mongo-secret
                key: mongo-pwd
          - name: DB_URL
            valueFrom: 
              configMapKeyRef: 
                name: mongo-config
                key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service # this is the end point that we defined in mongi-config.yaml
spec:
  type: NodePort
  selector: # uses this label selector to match right pod
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # matches the container port
      nodePort: 30100 # as per kubernetes 